### ISSUE TITLE
Get mentioned on blog post

### ISSUE THREAD

**Issue by nh2** [nh2/static-haskell-nix#11]
@vaibhavsagar Could you link https://github.com/nh2/static-haskell-nix on your blog post https://vaibhavsagar.com/blog/2018/01/03/static-haskell-nix/?

I keep finding people on the Internet that use it as a base for building statically (for example [here](https://github.com/BurntSushi/erd/issues/40#issue-399769490)), and they don't know that they can in most cases just clone `static-haskell-nix` and run 1 command to get the static exe they want ([example](https://github.com/BurntSushi/erd/issues/40#issuecomment-462060746)).

**Comment by vaibhavsagar** [comment]
Mentioned in https://github.com/vaibhavsagar/website/commit/bbf447ee185f658f17dad0e13e000139e4f08301.

May I suggest that you update your `README` to highlight that application of this repo? It currently states that this builds an "example application" and only further down does it point out that you can use it to build arbitrary packages. I didn't notice that section at all the first few times I looked at the `README` and mistakenly thought that this work was much less useful than it actually is.

**Comment by nh2** [comment]
Awesome, thanks, and good points. I've improved the README as suggested, please check it out!

**Comment by vaibhavsagar** [comment]
I like this much better, thanks!
