### ISSUE TITLE
cachix instructions should point to https://static-haskell-nix.cachix.org/

### ISSUE THREAD

**Issue by cdepillabout** [nh2/static-haskell-nix#49]
The instructions for using `cachix` in the README should link to https://static-haskell-nix.cachix.org/ instead of just https://cachix.org/.

https://static-haskell-nix.cachix.org/ gives actual instructions on how to install and setup `cachix`.

This is from https://github.com/cachix/cachix/issues/218.

**Comment by nh2** [comment]
Done.
