### ISSUE TITLE
nixpkgs glog package fails to build

### ISSUE THREAD

**Issue by mryndzionek** [nh2/static-haskell-nix#70]
Glog package fails to build due to missing [fix](https://github.com/google/glog/commit/834dd780bf1fe0704b8ed0350ca355a55f711a9f) that was added after v0.4.0 release

**Comment by nh2** [comment]
In which scenario / attrset / with which nixpkgs version?

**Comment by mryndzionek** [comment]
I'm using Nix 2.3.1 and script from `static-stack2nix-builder-example` without major modifications. It fails for [this](https://github.com/mryndzionek/hasscan) project. Glog is pulled in via opencv-0.0.2.1 bindings for Haskell. Let me know if I should post output from some specific Nix commands.

**Comment by nh2** [comment]
Thanks for the report.

This should fix it in nixpkgs: https://github.com/NixOS/nixpkgs/pull/75677

After it's merged there, I need to updated the pinned nixpkgs version used in `static-haskell-nix`.

**Comment by mryndzionek** [comment]
Great! Thanks! Waiting for the update then!

**Comment by nh2** [comment]
This update is certainly included now in the nixpkgs version that static-haskell-nix pins.
